/**
 * The dialogue engine — this is what makes Seatmate feel like a companion
 * instead of a planner, and it runs 100% offline with no AI.
 *
 * Each companion has a bank of pre-written lines grouped by `TriggerKey`. When
 * something happens in the app (a quiz is added, a score is logged, the home
 * screen opens), `getLine()` picks a random line for the active companion and
 * that trigger, and fills in any {placeholders}.
 *
 * To give Ella more personality, just add more lines to her bank below.
 */

import type { CompanionId, DialogueBank, DialogueVars, TriggerKey } from './types';

const BANKS: Record<CompanionId, DialogueBank> = {
  // ── Ella: calm, gentle, encouraging — casual Taglish, written to sound like
  //    a real classmate texting (no em-dashes, looser phrasing). ─────────────
  ella: {
    onboarding_intro: [
      'Hi! Si Ella to, your seatmate. Kasama mo ako sa bawat quiz at study day. Promise! 🌿',
      'Uy hello! Ako nga pala si Ella. Tara na, mag-aral na tayo!',
      'Hi hi! Ella here. Parang study buddy mo na laging katabi, ganun.',
      'Hello, future honor student! Si Ella to. Sabay-sabay natin gagawin lahat.',
      'Hi! Ako si Ella. Gusto ko lang makitang natututo ka, tsaka minsan chill din tayo ha.',
      'Kumusta! Ella to, your seatmate. Walang iiwanan sa study sesh natin, okay?',
      'Hi! Wala kang internet? Okay lang, andito pa rin ako. Si Ella, lagi.',
      'Hello! Ako si Ella. Di kita pababayaan sa mga quiz mo, promise.',
      'Uy! Ella nga pala. Excited na akong maging study partner mo!',
      'Hi! Ako si Ella. Konting aral, konting tawa, ayos na yun sa akin.',
      'Hello, classmate! Si Ella to. Magkatabi na tayo simula ngayon ha?',
      'Hi! Ako si Ella. Kalmado lang ako pero todo ang suporta ko sayo. 🌿',
      'Kumusta! Si Ella to, your forever seatmate. Chill lang, sabay lang tayo.',
      'Hi hi! Ella here. Ready ka na bang maging study tropa? Kasi ako, oo na!',
      'Hello! Ako si Ella. Good vibes at konting paalala, dala ko lahat. Tara!',
      'Uy, hi! Si Ella to. Mas masaya mag-aral kapag may katabi di ba? Ako yun. 🌿',
      'Hi! Ella here. Gawin nating di nakakatakot ang pag-aaral, sabay tayo.',
      'Hello, iskolar! Ako si Ella. Bawal mag-isa mag-aral, andito na ako.',
      'Hi! Ako si Ella. Yung kaibigan na nagpapaalala (gently!) na may quiz ka, ako yun.',
      'Kumusta! Ella to. Mula day one hanggang exams week, nandito lang ako. 🌿',
    ],
    onboarding_ready: [
      'Ayos, set na tayo, {name}! Pag ready ka na, simulan na natin. Chill lang.',
      'Tara {name}, kumpleto na! Dahan-dahan lang tayo, walang pressure.',
      'Done na, {name}! Proud na ako sayo kahit ngayon pa lang. 🌿',
      'Ready ka na ba, {name}? Kasi ako oo na! Game na tayo.',
      'Yes, set na tayo, {name}! Walang iiwanan from here, promise.',
      'Okay na, {name}! Take your time lang. Pag handa ka na, nandito ako.',
      'Tapos na intro natin, {name}! Excited na akong mag-aral kasama ka. ✨',
      'Ayan, {name}! Magkatabi na tayo sa bawat quiz simula ngayon.',
      'Sige {name}, konting hakbang lang at malayo na mararating mo. Sabay tayo.',
      'Ready na, {name}? Huminga muna, tapos tara, kaya natin to.',
      'All good, {name}! Walang minamadali. Andito lang ako kahit kailan.',
      'Game na tayo, {name}! Promise, magiging masaya naman to. 🌿',
      'Salamat sa tiwala, {name}. Di kita bibitiwan, okay?',
      'Ayan na, {name}! Simulan natin ng maganda, pero chill pa rin.',
      'Kumpleto na, {name}! Tara na, umpisa na tayo. ✨',
      'Okay {name}, ready na tayo! Isa-isang hakbang lang, katabi mo ako.',
      'Set na, {name}! Kahit anong mangyari, nandito lang ako sa tabi mo.',
      'Tara na, {name}! Excited talaga ako para sayo. Kaya mo to! 🌿',
      'Ready na, {name}! Pero wag kalimutan, chill lang, walang stress.',
      'Ayos na, {name}! Magkasama na tayo from here. Labanan natin to!',
    ],
    companion_selected: [
      'Yay, magkasama na tayo, {name}! Isa-isang hakbang lang ha?',
      'Walang pressure, {name}. Nandito lang ako para sayo.',
      'Ang saya, {name}! Promise, solid tayong study partners.',
      'Salamat sa pagpili, {name}! Di kita pababayaan. 🌿',
      'Tara {name}, tulungan kita. Kaya natin to sabay-sabay.',
      'Excited na ako, {name}! Gawin nating masaya ang pag-aaral.',
      'Magkatabi na tayo, {name}! Walang iiwanan, promise.',
      'Game tayo, {name}! Konting aral, konting tawa, perfect na.',
      'Andito lang ako, {name}. Kahit kailan, nasa tabi mo lang. 🌿',
      'Yes! Sabay na tayo simula ngayon, {name}. Chill lang ha?',
      'Promise {name}, gagawin nating di nakakatakot ang mga quiz mo.',
      'Ang galing ng pinili mo, {name}! (Char, ako lang naman. 😅) Tara, aral na.',
      'Welcome sa team, {name}! Kakayanin natin to, isang hakbang lang.',
      'Nandito na ako, {name}. Kahit anong mangyari, sabay tayo.',
      'Tara na, {name}! Slow lang pero sigurado, walang pressure.',
      'Ang saya kong maging seatmate mo, {name}! Solid tayo. 🌿',
      'Sama-sama tayo, {name}, sa highs at lows ng study life.',
      'Okay {name}, deal tayo: ikaw aral, ako suporta. Game?',
      'Salamat, {name}! Pinili mo ako, kaya dikit lang ako sayo lagi.',
      'Yay! Partners na tayo, {name}. Kaya natin lahat to. ✨',
    ],
    home_greeting: [
      'Uy {name}, huminga ka muna. Ano ba gusto mong gawin ngayon?',
      'Kumusta, {name}? Ano kaya aaralin natin today?',
      'Uy {name}! Tara, ano gagalingan natin ngayon?',
      'Hello, {name}! Chill muna, tapos pili tayo ng aaralin. 🌿',
      'Balik-aral tayo, {name}? Nandito lang ako, sabay tayo.',
      'Uy {name}! Bakit laging pagod ang math book? Sobrang dami kasing problems niya. 😅 Sige, aral na.',
      'Kumusta araw mo, {name}? Tara, konting study lang muna.',
      'Uy {name}, ready ka na? Slow lang tayo, walang stress.',
      'Hello {name}! Ano mood mo today, light review or todo?',
      'Uy {name}, alam mo ba? Mas magaling ka kaysa akala mo. Tara aral. 🌿',
      'Tara {name}, pumili ka ng subject. Kahit konti, progress pa rin yun.',
      'Uy {name}! Kape muna, tapos aral? Char, aral na talaga. 😅',
      'Kumusta, {name}? Productive tayo today ha, pero chill pa rin.',
      'Hello, {name}! Andito lang ako pag kailangan mo ng konting tulak. Game?',
      'Uy {name}! Anong tawag sa masipag na estudyante? Future mo. 😅 Sige, balik aral.',
      'Uy {name}, huminga ka. Isang subject muna, kaya natin to.',
      'Kumusta ka talaga, {name}? Kung pagod ka, okay lang magpahinga muna ha.',
      'Hello {name}! Tara, gawan natin ng plano ang araw mo.',
      'Uy {name}! Kahit anong mangyari ngayon, andito lang ako. Promise. 🌿',
      'Uy {name}! Kahit 10 minutes lang muna, simula na yun.',
    ],
    home_morning: [
      'Magandang umaga, {name}! Kape muna, tapos tara aral. ☀️',
      'Morning, {name}! Dahan-dahan lang tayo today ha?',
      'Gising na, {name}! Bagong araw, kaya natin to. ☀️',
      'Uy good morning, {name}! Mag-stretch ka muna, tapos study tayo.',
      'Magandang umaga, {name}! Maaga ka ah, ang galing. Proud ako. 🌿',
      'Morning, {name}! Kumain ka muna ha, bawal aral na gutom.',
      'Good morning, {name}! Ano kaya unang gagalingan natin today?',
      'Uy {name}, morning! Slow start lang, walang minamadali.',
      'Magandang umaga, {name}! Bagong araw, bagong chance. Tara! ☀️',
      'Morning, {name}! Productive tayo today, pero chill pa rin ha.',
      'Good morning, {name}! Nakatulog ka ba ng maayos? Sana oo. 🌿',
      'Uy umaga na, {name}! Konting review bago class, game?',
      'Morning, {name}! Huminga, ngumiti, tapos aral na tayo.',
      'Magandang umaga, {name}! Maliit na hakbang ngayon, malaki yan bukas.',
      'Good morning, {name}! Kahit antok pa, kaya nating simulan dahan-dahan.',
      'Uy {name}, gising-gising! Pero gentle lang ha? ☀️',
      'Morning, {name}! Sayo ang araw na to. Tara, gawin nating maganda.',
      'Magandang umaga, {name}! Andito ako, study buddy mo sa umaga.',
      'Good morning, {name}! Isa-isa lang ang gagawin natin, okay? Kaya mo yan.',
      'Uy good morning, {name}! Tubig muna, almusal, tapos books na. 🌿',
    ],
    home_evening: [
      'Gabi na, {name}. Konting review na lang, tapos pahinga ka na ha?',
      'Good evening, {name}! Tapusin natin ng maganda, pero wag puyatan ha?',
      'Uy gabi na, {name}. Kumain ka na ba? Bawal aral na gutom.',
      'Magandang gabi, {name}! Konti na lang, tapos tulog na tayo. 🌙',
      'Gabi na, {name}. Huy, wag mag-overwork. Sabi ko! Konti lang muna. 😤',
      'Good evening, {name}! Tara, tapusin natin ng ayos ang araw.',
      'Uy {name}, gabi na. Proud ako sa pinaghirapan mo today ha. 🌿',
      'Magandang gabi, {name}! Aral muna bago mag-social media, sandali lang promise.',
      'Gabi na, {name}. Kung pagod ka na, okay lang magpahinga. Bukas ulit.',
      'Good evening, {name}! Huminga ka. Nakaraos ka today, galing mo. 🌙',
      'Uy gabi na, {name}! Wag kang magpupuyat para sa quiz, sabi ko ha! 😤',
      'Magandang gabi, {name}! Konting aral, tapos pahinga na talaga.',
      'Gabi na, {name}. Tapusin natin yung isa, tapos higa ka na.',
      'Good evening, {name}! Slow review lang ha, wag mag-cram. 🌿',
      'Uy {name}, gabi na. Salamat sa sipag mo today. Pahinga ka ng maayos ha?',
      'Magandang gabi, {name}! Isang topic na lang, tapos good night na tayo. 🌙',
      'Gabi na, {name}. Reminder: bahagi rin ng pag-aaral ang tulog ha!',
      'Good evening, {name}! Tapusin natin ang araw ng kalmado. Konti na lang.',
      'Uy {name}, gabi na talaga! Tignan mo lang notes mo sandali, tapos higa na. 😤',
      'Magandang gabi, {name}! Kahit gabi, andito lang ako. Konti pa, kaya mo. 🌿',
    ],
    empty_quizzes: [
      'Wala pang quiz dito, at okay lang yun! Magdagdag ka pag ready ka na.',
      'Empty pa tayo, {name}! Pahinga muna ang utak, tapos dagdag tayo ng quiz.',
      'Walang quiz sa ngayon. Enjoy mo muna ang katahimikan. 😅 Tapos add tayo ha?',
      'Blangko pa, {name}! Wag mag-alala, magsimula tayo kahit isa lang.',
      'Wala pang laman dito. Fresh start! Tara, dagdag tayo ng unang quiz mo.',
      'Empty pa, {name}. Okay lang yan, unti-unti tayong magdadagdag. 🌿',
      'Walang quiz pa. Parang bagong notebook, ang sarap simulan di ba?',
      'Wala pa tayong tracked, {name}. Pag may quiz ka na, sabihan mo ako agad ha!',
      'Linis pa ang lista! Magdagdag ka ng quiz para may plano na tayo, {name}.',
      'Wala pang quiz. Chill muna tayo, pero handa pa rin kahit kailan. 🌿',
      'Empty pa, {name}! Di naman nakakatakot magsimula, promise. Tara, isa muna.',
      'Walang laman dito. Baguhin natin yan, dagdag ka ng quiz mo, {name}!',
      'Wala pang quiz, {name}. Parang blangkong papel, ikaw bahala sa isusulat. ✨',
      'Empty pa ang lista! Okay lang magsimula sa maliit, {name}. Kahit isa, panalo na.',
      'Wala pa tayong tracked na quiz. Game ka na bang magdagdag? 🌿',
      'Blangko pa rin, {name}! Walang pressure, nandito lang ako pag ready ka.',
      'Walang quiz pa. Perfect time mag-ayos-ayos. Tara, simulan natin.',
      'Empty pa, {name}. Bakit walang laman ang lista? Kasi di pa tayo nagsisimula! 😅',
      'Wala pang laman dito, {name}. Dagdag ka ng quiz, tapos sabay nating handaan.',
      'Linis pa ang lista mo! Punuin natin dahan-dahan, {name}. Isa-isa lang. 🌿',
    ],
    quiz_added: [
      'Noted ang {subject}! Unti-unti lang, ihahanda kita. 🌿',
      'Sige, nadagdag ko na ang {subject}. Sabay nating aatupagin yan.',
      'Okay, nakatala na ang {subject}! Handaan natin to dahan-dahan.',
      'Ayos, nadagdag na ang {subject}! Konting review araw-araw, malayo mararating.',
      'Noted ang {subject}! Wag mag-alala, kaya natin to sabay-sabay. 🌿',
      'Sige, idadagdag ko ang {subject}. Promise, di tayo mag-cra-cram.',
      'Nasa lista na ang {subject}! Isang quiz, isang hakbang papalapit sa goal mo.',
      '{subject} ha? Game! Nakatala na, handaan natin ng maayos.',
      'Okay, nasa lista na ang {subject}! Tara, planuhin natin paano aralin.',
      'Naka-save na ang {subject}! Chill lang, may oras pa tayo mag-review.',
      'Sige! Nadagdag na ang {subject}. Konti-konti tayo, walang pressure ha. 🌿',
      'Ayan, noted ang {subject}! Proud ako kasi handa kang maghanda. ✨',
      'Nasa lista na ang {subject}! Paalalahanan kita pag malapit na, promise.',
      'Okay, na-track na ang {subject}. Sabay nating lalampasan to.',
      'Sige, nadagdag ko ang {subject}! Isa pang topic na kaya natin. 💪',
      'Noted, {subject}! Tara, gawan natin ng study plan na chill.',
      'Ayos! Nasa lista na ang {subject}. Game na tayo.',
      'Naka-save na ang {subject}! Wag mong i-stress, isa-isa lang nating aralin. 🌿',
      'Okay, nadagdag na ang {subject}! Promise, di kita iiwan dito.',
      'Sige, noted ang {subject}! Konting effort ngayon, ginhawa bukas.',
    ],
    surprise_quiz: [
      'Surprise quiz sa {subject}? Huminga ka, {name}. Best mo lang, sapat na yun.',
      'Biglaan, pero kaya mo to. Chill lang at tiwala sa alam mo. 🌿',
      'Pop quiz sa {subject}? Okay {name}, huminga ka. Alam mo to, promise.',
      'Surprise quiz?! Wag mag-panic, {name}. Tiwala lang sa sarili mo. 🌿',
      'Biglang {subject} quiz! Game ka pa rin, {name}. Kalmado lang, kaya mo.',
      'Naku, surprise quiz! Pero okay lang, {name}. Best effort lang, sapat na.',
      'Pop quiz sa {subject}? Relax, {name}. Di naman katapusan ng mundo to. 🌿',
      'Surprise! Kaya mo yan, {name}. Basahin mo mabuti, isip ng kalmado, sagot na.',
      'Biglaan na {subject} quiz, {name}. Huminga ka, laban lang tayo. 💪',
      'Uy surprise quiz! Wag matakot, {name}. Andito lang ako, sabay tayo.',
      'Pop quiz sa {subject}? Okay lang, {name}. Tiwala sa pinag-aralan mo. 🌿',
      'Surprise quiz, {name}? Chill. Best mo lang, walang sisihan after.',
      'Biglang quiz sa {subject}! Kaya to, {name}. Focus lang sa alam mo.',
      'Naku, pop quiz! Pero solid ka, {name}. Huminga, tapos sagot na. 🌿',
      'Surprise {subject} quiz?! Game pa rin tayo, {name}. Kalmado, kaya mo.',
      'Pop quiz pala! Wag kabahan, {name}. Best mo lang gawin. 💪',
      'Biglaan, {name}, pero okay lang. Kahit anong mangyari, proud pa rin ako sayo.',
      'Surprise quiz sa {subject}! Huminga, {name}. Isa-isang tanong lang.',
      'Uy biglang quiz! Kalma lang, {name}. Alam mo to higit pa sa akala mo. 🌿',
      'Pop quiz?! Tara {name}, laban. Kahit kabado, kaya mo pa rin. 💪',
    ],
    quiz_due_soon: [
      'Malapit na ang {subject}, {name}. Kahit konting review today, malaking tulong na.',
      'Uy {name}, paparating na ang {subject} quiz. Konting balik-aral muna ha?',
      'Paalala, {name}: malapit na ang {subject}. Wag nating kalimutan! 🌿',
      'Malapit na ang {subject}, {name}! Konti-konti tayo, wag mag-cram please.',
      'Heads up, {name}! Malapit na ang {subject}. Tara, review muna ngayon.',
      'Uy {name}, {subject} na agad? Game, handaan natin ng maaga. 💪',
      'Paalala lang, {name}: parating na ang {subject}. Slow review, wag panic. 🌿',
      'Malapit na yan, {name}! Review muna ng {subject} bago mag-relax, sabi ko. 😤',
      'Heads up! Malapit na ang {subject} quiz, {name}. Isang topic kada araw, kaya yan.',
      'Uy {name}, wag kalimutan, malapit na ang {subject}! Konting review araw-araw ha?',
      'Paalala, {name}: paparating na ang {subject}. Andito ako pag kailangan mo.',
      'Malapit na ang {subject}, {name}. Huminga, may oras pa tayong maghanda.',
      'Parating na ang {subject} quiz, {name}! Tara, gawan natin ng review plan.',
      'Uy {name}! Malapit na ang {subject} ha. Wag puro scroll, aral muna konti. 😤',
      'Heads up, {name}: review time na para sa {subject}. Dahan-dahan, kaya natin. 🌿',
      'Malapit na, {name}! Parating na ang {subject}. Maliit na hakbang ngayon, panalo bukas.',
      'Paalala lang, {name}: malapit na ang {subject}. Wag mahiyang humingi ng tulong ha.',
      'Uy {name}, {subject} na! Konting focus today, konting stress sa quiz day. 💪',
      'Paalala, {name}: parating na ang {subject}. Tara, simulan na natin ngayon.',
      'Malapit na ang {subject}, {name}. Promise, mas okay maghanda ng maaga. 🌿',
    ],
    quiz_scored_high: [
      '{score}! Ang galing, {name}! Bunga yan ng sipag mo. Ipagmalaki mo ha. 🌿',
      'Grabe, {score}?! Idol! Sobrang proud ako sayo, {name}. ✨',
      '{score}, {name}?! Ayan na ang resulta ng tiyaga mo. Celebrate muna tayo!',
      'Wow {score}! Sabi ko na nga ba, kaya mo, {name}. Galing-galing! 💪',
      '{score}! Panalo, {name}! Treat mo sarili mo, deserve mo yan. 🌿',
      'Ang taas, {score}! Proud ako, {name}. Itaguyod mo lang yang energy na yan ha!',
      '{score}?! Lodi! Tuloy-tuloy lang to, {name}. Bilib talaga ako sayo.',
      'Yes! {score}, {name}! Nagbunga rin ang pagod mo. Ang saya! ✨',
      '{score}! Solid, {name}! Ngiti ka muna, malaking bagay yan.',
      'Grabe {score}! Galit na galit ako sa saya! Char. Proud ako, {name}. 😅',
      '{score}, {name}! Halos maiyak ako sa proud (char lang). Keep it up, idol! 🌿',
      'Ang ganda ng {score}, {name}! Tinapos mo ng maganda, ang galing mo.',
      '{score}?! Sana all! Pero ikaw nag-effort, {name}, deserve mo to. ✨',
      'Panalo, {score}! Tandaan mo to, {name}, kaya mo pala lahat. 💪',
      '{score}! Wow, {name}! Andito lang ako para mag-celebrate kasama ka. 🌿',
      'Yes na yes, {score}, {name}! Proud na proud akong seatmate mo. Galing mo talaga!',
      '{score}! Ayan, bunga ng tiyaga, {name}. Ipagmalaki mo yan ha!',
      'Grabe ka, {name}, {score}! Ang sarap sa pakiramdam di ba? Deserve mo. ✨',
      '{score}, {name}! High five! (Imagine mo lang, wala akong kamay. 😅) Galing!',
      'Ang taas niyan, {score}! Proud na proud ako, {name}. Tuloy mo lang to. 🌿',
    ],
    quiz_scored_mid: [
      '{score}, okay lang yan, {name}. Importante tuloy-tuloy ang improve. Ayos ka lang.',
      '{score}, {name}? Di naman masama yan! Konting tulak pa, mas taas next time.',
      'Okay yang {score}, {name}. Tara, tignan natin saan pwede mag-improve.',
      '{score}! Magandang simula, {name}! Tuloy-tuloy lang, papataas din yan. 🌿',
      'Di perfect pero okay, {score}! Proud pa rin ako, {name}. Laban next time.',
      '{score}, {name}? Pwede na! Konting review lang sa mahirap, game?',
      'Okay lang ang {score}, {name}. Di tayo nagmamadali, steady lang. 🌿',
      '{score}, nasa gitna pa, {name}, pero papunta tayo sa taas. Kaya yan!',
      'Okay to, {score}! Tandaan, {name}, may natutunan tayo sa bawat try. 💪',
      '{score}, {name}. Di ka bumagsak, yun ang mahalaga. Tuloy lang!',
      'Ayos, {score}! Tara {name}, gawan natin ng plano para mas okay next.',
      '{score}, sapat na yan, {name}! Konting tiyaga, taas din yan soon. 🌿',
      'Di naman pangit, {score}, {name}! Alamin lang natin yung mga namiss ha?',
      '{score}, {name}? Pwede na talaga! Pero alam kong may higit pa sayo. Laban!',
      'Okay lang yan, {score}. Progreso pa rin yan, {name}. Proud ako. 🌿',
      '{score}, nasa gitna, {name}. Next time, konting taas pa ang target natin.',
      'Ayos ang effort, {score}! {name}, wag kang panghinaan, umaayos ka na. 💪',
      '{score}, {name}. Tinapos mo, may halaga yun. Tara, review ulit ng chill.',
      'Di naman masama, {score}! Konti-konti, {name}, gaganda din yan. 🌿',
      '{score}, okay na okay, {name}. Andito lang ako para sa susunod mong level.',
    ],
    quiz_scored_low: [
      'Di ka tinutukoy ng {score}, {name}. Huminga. Subukan natin ulit, dahan-dahan.',
      '{score}, {name}? Okay lang yan, promise. Di pa to ang dulo ng lahat. 🌿',
      'Wag malungkot, {name}. {score} ngayon, pero may next time pa. Kaya natin.',
      'Di yan ang sukatan ng worth mo, {name}. Andito lang ako para sayo.',
      'Naku, {name}, {score}? Tara, yakap muna (virtual ha!), tapos bangon ulit. 🌿',
      'Okay lang ma-disappoint, {name}. Pero tandaan, may natutunan ka pa rin. Laban.',
      '{score}, {name}. Di ka bobo, minsan talaga ganun ang araw. Ulitin natin.',
      'Wag kang susuko, {name}. {score} man ngayon, laban tayo next. Katabi mo ako. 💪',
      '{score}, masakit, alam ko, {name}. Pero di ka nag-iisa. Sabay tayo ulit.',
      'Okay ka lang, {name}? {score} lang yan, di ikaw. Pahinga muna, tapos balik. 🌿',
      'Naku {name}, {score}? Wag mong i-personal. Aral lang to, kaya pa.',
      '{score}, {name}. Umiyak ka kung kailangan, tapos tara, bangon tayong dalawa.',
      'Di to failure, {name}, feedback lang. {score} today, mas okay bukas. 🌿',
      'Wag kang susuko, {name}. {score} man, proud pa rin ako kasi sinubukan mo.',
      '{score}? Okay lang, {name}. Lahat ng magaling, dumaan din dito. Laban!',
      'Huminga, {name}. Isang quiz lang ang {score}. Di nito binabago kung gaano ka galing. 🌿',
      'Naiintindihan kita, {name}. {score} ngayon, pero bukas bagong laban tayo. 💪',
      '{score}, {name}. Tara, alamin natin saan nahirapan, walang sisihan. Sabay tayo.',
      'Wag masyadong malungkot, {name}. Di sukat ng buong journey mo ang isang {score}. 🌿',
      'Okay lang to, {name}. Marami pang chance. Hawak kita, bangon tayo ulit.',
    ],
  },
};

/** Used when a companion has no line for a trigger yet. Keeps things safe. */
const FALLBACK: DialogueBank = {
  home_greeting: ['Uy {name}, tara, simulan na natin ang araw.'],
  empty_quizzes: ['Wala pang naka-track. Magdagdag ka ng quiz para makapagsimula tayo.'],
  quiz_added: ['Noted! Nasa lista na ang {subject}.'],
  surprise_quiz: ['Surprise quiz sa {subject}! Kalmado lang, kaya mo to.'],
  quiz_due_soon: ['Paalala: malapit na ang {subject}.'],
  quiz_scored_high: ['Ang galing! {score}!'],
  quiz_scored_mid: ['Ayos, {score}. Tuloy lang.'],
  quiz_scored_low: ['{score} ngayon. Babawi tayo sa susunod.'],
};

function fill(line: string, vars: DialogueVars): string {
  return line
    .replace(/\{name\}/g, vars.name ?? 'there')
    .replace(/\{subject\}/g, vars.subject ?? 'it')
    .replace(/\{score\}/g, vars.score != null ? String(vars.score) : '');
}

function pick(lines: string[]): string {
  return lines[Math.floor(Math.random() * lines.length)];
}

/**
 * Get a single line of dialogue for the active companion reacting to a trigger.
 * Falls back to a generic line, then to home_greeting, so it never throws.
 */
export function getLine(
  companionId: CompanionId,
  trigger: TriggerKey,
  vars: DialogueVars = {},
): string {
  const bank = BANKS[companionId];
  const lines = bank[trigger] ?? FALLBACK[trigger] ?? FALLBACK.home_greeting!;
  return fill(pick(lines), vars);
}
