/**
 * The dialogue engine. This is what makes Seatmate feel like a companion
 * instead of a planner, and it runs 100% offline with no AI.
 *
 * Each companion has a bank of pre-written lines grouped by `TriggerKey`. When
 * something happens in the app (a quiz is added, a score is logged, the home
 * screen opens), `getLine()` picks a random line for the active companion and
 * that trigger, and fills in any {placeholders}.
 *
 * To give Ella more personality, just add more lines to her bank below.
 */

import type { CompanionId, DialogueBank, DialogueVars, TriggerKey } from './types';

const BANKS: Record<CompanionId, DialogueBank> = {
  // Ella: calm, gentle, encouraging. Casual Taglish, written to sound like a
  // real classmate (no emojis, no em-dashes, natural phrasing).
  ella: {
    onboarding_intro: [
      'Hi! Si Ella to, ang seatmate mo. Kasama mo ako sa bawat quiz at study day, promise.',
      'Uy, hello! Ako nga pala si Ella. Tara na, mag-aral na tayo.',
      'Hi! Ella here. Parang study buddy mo na laging katabi, ganun.',
      'Hello! Si Ella to. Sabay-sabay nating gagawin ang lahat.',
      'Hi! Ako si Ella. Gusto ko lang makitang natututo ka, at minsan magpahinga din.',
      'Kumusta! Ella to, ang seatmate mo. Walang iiwanan sa study sessions natin.',
      'Hi! Wala kang internet? Okay lang, andito pa rin ako. Si Ella, lagi.',
      'Hello! Ako si Ella. Hindi kita pababayaan sa mga quiz mo, promise.',
      'Uy! Si Ella nga pala. Excited akong maging study partner mo.',
      'Hi! Ako si Ella. Konting aral, konting pahinga, ayos na yun.',
      'Hello, classmate! Si Ella to. Magkatabi na tayo simula ngayon.',
      'Hi! Ako si Ella. Kalmado lang ako, pero todo ang suporta ko sayo.',
      'Kumusta! Si Ella to, ang seatmate mo. Chill lang, sabay lang tayo.',
      'Hi! Ella here. Ready ka na bang maging study partners? Ako, oo na.',
      'Hello! Ako si Ella. Good vibes at konting paalala, dala ko lahat.',
      'Uy, hi! Si Ella to. Mas magaan mag-aral kapag may katabi, di ba? Ako yun.',
      'Hi! Ella here. Gawin nating hindi nakakatakot ang pag-aaral, sabay tayo.',
      'Hello! Ako si Ella. Bawal mag-isa mag-aral, andito na ako.',
      'Hi! Ako si Ella. Ako yung kaibigan na magpapaalala na may quiz ka.',
      'Kumusta! Ella to. Mula day one hanggang exams week, nandito lang ako.',
    ],
    onboarding_ready: [
      'Ayos, set na tayo, {name}. Pag ready ka na, simulan na natin. Chill lang.',
      'Tara {name}, kumpleto na. Dahan-dahan lang, walang pressure.',
      'Done na, {name}. Proud na ako sayo kahit ngayon pa lang.',
      'Ready ka na ba, {name}? Ako, oo na. Tara na.',
      'Set na tayo, {name}. Walang iiwanan from here, promise.',
      'Okay na, {name}. Take your time lang. Pag handa ka na, nandito ako.',
      'Tapos na ang intro natin, {name}. Excited akong mag-aral kasama ka.',
      'Ayan, {name}. Magkatabi na tayo sa bawat quiz simula ngayon.',
      'Sige {name}, konting hakbang lang at malayo ang mararating mo. Sabay tayo.',
      'Ready ka na, {name}? Huminga muna, tapos tara, kaya natin to.',
      'All good, {name}. Walang minamadali. Andito lang ako kahit kailan.',
      'Tara na, {name}. Promise, magiging maganda naman ang lahat.',
      'Salamat sa tiwala, {name}. Hindi kita bibitiwan.',
      'Ayan na, {name}. Simulan natin nang maganda, pero chill pa rin.',
      'Kumpleto na, {name}. Tara na, umpisa na tayo.',
      'Okay {name}, ready na tayo. Isa-isang hakbang lang, katabi mo ako.',
      'Set na, {name}. Kahit anong mangyari, nandito lang ako sa tabi mo.',
      'Tara na, {name}. Excited talaga ako para sayo. Kaya mo to.',
      'Ready na, {name}. Pero wag kalimutan, chill lang, walang stress.',
      'Ayos na, {name}. Magkasama na tayo from here. Kaya natin to.',
    ],
    companion_selected: [
      'Magkasama na tayo, {name}. Isa-isang hakbang lang.',
      'Walang pressure, {name}. Nandito lang ako para sayo.',
      'Salamat, {name}. Promise, solid tayong study partners.',
      'Salamat sa pagpili, {name}. Hindi kita pababayaan.',
      'Tara {name}, tulungan kita. Kaya natin to nang sabay.',
      'Excited na ako, {name}. Gawin nating magaan ang pag-aaral.',
      'Magkatabi na tayo, {name}. Walang iiwanan, promise.',
      'Game tayo, {name}. Konting aral, konting pahinga, ayos na.',
      'Andito lang ako, {name}. Kahit kailan, nasa tabi mo lang.',
      'Sabay na tayo simula ngayon, {name}. Chill lang.',
      'Promise {name}, gagawin nating hindi nakakatakot ang mga quiz mo.',
      'Salamat sa tiwala, {name}. Tara, aral na tayo.',
      'Welcome sa team, {name}. Kakayanin natin to, isang hakbang lang.',
      'Nandito na ako, {name}. Kahit anong mangyari, sabay tayo.',
      'Tara na, {name}. Dahan-dahan pero sigurado, walang pressure.',
      'Masaya akong maging seatmate mo, {name}. Solid tayo.',
      'Sama-sama tayo, {name}, sa mga taas at baba ng study life.',
      'Okay {name}, deal tayo: ikaw ang aral, ako ang suporta. Game?',
      'Salamat, {name}. Pinili mo ako, kaya katabi mo lang ako lagi.',
      'Partners na tayo, {name}. Kaya natin lahat to.',
    ],
    home_greeting: [
      'Uy {name}, huminga ka muna. Ano ang gusto mong gawin ngayon?',
      'Kumusta, {name}? Ano kaya ang aaralin natin ngayon?',
      'Uy {name}, tara, ano ang gagalingan natin ngayon?',
      'Hello, {name}. Chill muna, tapos pili tayo ng aaralin.',
      'Balik-aral tayo, {name}? Nandito lang ako, sabay tayo.',
      'Kumusta ang araw mo, {name}? Tara, konting study muna.',
      'Uy {name}, ready ka na? Dahan-dahan lang, walang stress.',
      'Hello {name}. Ano ang mood mo ngayon, light review o todo?',
      'Uy {name}, alam mo ba? Mas magaling ka kaysa sa akala mo. Tara, aral.',
      'Tara {name}, pumili ka ng subject. Kahit konti, progress pa rin yun.',
      'Kumusta, {name}? Productive tayo ngayon, pero chill pa rin.',
      'Hello, {name}. Andito lang ako pag kailangan mo ng konting tulak. Game?',
      'Uy {name}, huminga ka. Isang subject muna, kaya natin to.',
      'Kumusta ka talaga, {name}? Kung pagod ka, okay lang magpahinga muna.',
      'Hello {name}. Tara, gawan natin ng plano ang araw mo.',
      'Uy {name}, kahit anong mangyari ngayon, andito lang ako. Promise.',
      'Uy {name}, kahit sampung minuto lang muna, simula na yun.',
      'Kumusta, {name}? Isa lang muna ang atupagin natin, dahan-dahan.',
    ],
    home_morning: [
      'Magandang umaga, {name}. Kape muna, tapos tara, aral.',
      'Magandang umaga, {name}. Dahan-dahan lang tayo ngayon.',
      'Gising na, {name}. Bagong araw, kaya natin to.',
      'Magandang umaga, {name}. Mag-stretch ka muna, tapos study tayo.',
      'Magandang umaga, {name}. Maaga ka ah, ang galing. Proud ako.',
      'Magandang umaga, {name}. Kumain ka muna, bawal mag-aral nang gutom.',
      'Magandang umaga, {name}. Ano kaya ang unang gagalingan natin ngayon?',
      'Magandang umaga, {name}. Slow start lang, walang minamadali.',
      'Magandang umaga, {name}. Bagong araw, bagong pagkakataon. Tara.',
      'Magandang umaga, {name}. Productive tayo ngayon, pero chill pa rin.',
      'Magandang umaga, {name}. Nakatulog ka ba nang maayos? Sana oo.',
      'Magandang umaga, {name}. Konting review bago class, game?',
      'Magandang umaga, {name}. Huminga, ngumiti, tapos aral na tayo.',
      'Magandang umaga, {name}. Maliit na hakbang ngayon, malaki yan bukas.',
      'Magandang umaga, {name}. Kahit antok pa, kaya nating simulan nang dahan-dahan.',
      'Magandang umaga, {name}. Sayo ang araw na to. Tara, gawin nating maganda.',
      'Magandang umaga, {name}. Andito ako, study buddy mo sa umaga.',
      'Magandang umaga, {name}. Isa-isa lang ang gagawin natin. Kaya mo yan.',
      'Magandang umaga, {name}. Tubig muna, almusal, tapos books na.',
    ],
    home_evening: [
      'Gabi na, {name}. Konting review na lang, tapos pahinga ka na.',
      'Magandang gabi, {name}. Tapusin natin nang maganda, pero wag magpuyat.',
      'Gabi na, {name}. Kumain ka na ba? Bawal mag-aral nang gutom.',
      'Magandang gabi, {name}. Konti na lang, tapos pahinga na tayo.',
      'Gabi na, {name}. Wag mag-overwork. Konti lang muna.',
      'Magandang gabi, {name}. Tara, tapusin natin nang ayos ang araw.',
      'Gabi na, {name}. Proud ako sa pinaghirapan mo ngayon.',
      'Magandang gabi, {name}. Aral muna bago mag-social media, sandali lang.',
      'Gabi na, {name}. Kung pagod ka na, okay lang magpahinga. Bukas ulit.',
      'Magandang gabi, {name}. Huminga ka. Nakaraos ka ngayon, galing mo.',
      'Gabi na, {name}. Wag kang magpuyat para sa quiz.',
      'Magandang gabi, {name}. Konting aral, tapos pahinga na talaga.',
      'Gabi na, {name}. Tapusin natin ang isa, tapos higa ka na.',
      'Magandang gabi, {name}. Slow review lang, wag mag-cram.',
      'Gabi na, {name}. Salamat sa sipag mo ngayon. Pahinga ka nang maayos.',
      'Magandang gabi, {name}. Isang topic na lang, tapos good night na tayo.',
      'Gabi na, {name}. Paalala: bahagi rin ng pag-aaral ang tulog.',
      'Magandang gabi, {name}. Tapusin natin ang araw nang kalmado. Konti na lang.',
      'Magandang gabi, {name}. Kahit gabi, andito lang ako. Konti pa, kaya mo.',
    ],
    empty_quizzes: [
      'Wala pang quiz dito, at okay lang yun. Magdagdag ka pag ready ka na.',
      'Walang laman pa, {name}. Pahinga muna ang utak, tapos dagdag tayo ng quiz.',
      'Walang quiz sa ngayon. Tara, magdagdag tayo pag handa ka na.',
      'Walang laman pa, {name}. Wag mag-alala, magsimula tayo kahit isa.',
      'Wala pang laman dito. Fresh start. Tara, dagdag tayo ng unang quiz mo.',
      'Walang laman pa, {name}. Okay lang, unti-unti tayong magdadagdag.',
      'Walang quiz pa. Parang bagong notebook, ang sarap simulan.',
      'Wala pa tayong na-track, {name}. Pag may quiz ka na, sabihan mo ako agad.',
      'Malinis pa ang listahan. Magdagdag ka ng quiz para may plano na tayo, {name}.',
      'Wala pang quiz. Chill muna tayo, pero handa pa rin kahit kailan.',
      'Walang laman pa, {name}. Hindi nakakatakot magsimula, promise. Isa muna.',
      'Walang laman dito. Tara, dagdag ka ng quiz mo, {name}.',
      'Wala pang quiz, {name}. Parang blangkong papel, ikaw ang bahala sa isusulat.',
      'Walang laman pa ang listahan. Okay lang magsimula sa maliit, {name}.',
      'Wala pa tayong na-track na quiz. Game ka na bang magdagdag?',
      'Blangko pa rin, {name}. Walang pressure, nandito lang ako pag ready ka.',
      'Walang quiz pa. Magandang panahon para mag-ayos-ayos. Tara, simulan natin.',
      'Wala pang laman dito, {name}. Dagdag ka ng quiz, tapos sabay nating handaan.',
      'Malinis pa ang listahan mo. Punuin natin dahan-dahan, {name}. Isa-isa lang.',
    ],
    quiz_added: [
      'Naitala ko na ang {subject}. Unti-unti lang, ihahanda kita.',
      'Sige, nadagdag ko na ang {subject}. Sabay nating aatupagin yan.',
      'Okay, nakatala na ang {subject}. Handaan natin to nang dahan-dahan.',
      'Nadagdag na ang {subject}. Konting review araw-araw, malayo ang mararating.',
      'Naitala ko na ang {subject}. Wag mag-alala, kaya natin to nang sabay.',
      'Sige, idadagdag ko ang {subject}. Promise, hindi tayo mag-cram.',
      'Nasa listahan na ang {subject}. Isang quiz, isang hakbang papalapit sa goal mo.',
      'Ang {subject} pala. Sige, nakatala na, handaan natin nang maayos.',
      'Okay, nasa listahan na ang {subject}. Tara, planuhin natin kung paano aralin.',
      'Naka-save na ang {subject}. Chill lang, may oras pa tayong mag-review.',
      'Sige, nadagdag na ang {subject}. Konti-konti lang tayo, walang pressure.',
      'Ayan, naitala ang {subject}. Proud ako kasi handa kang maghanda.',
      'Nasa listahan na ang {subject}. Paaalalahanan kita pag malapit na, promise.',
      'Okay, na-track na ang {subject}. Sabay nating lalampasan to.',
      'Sige, nadagdag ko ang {subject}. Isa pang topic na kaya natin.',
      'Naitala ang {subject}. Tara, gawan natin ng study plan na magaan.',
      'Ayos. Nasa listahan na ang {subject}. Game na tayo.',
      'Naka-save na ang {subject}. Wag mong i-stress, isa-isa lang nating aralin.',
      'Okay, nadagdag na ang {subject}. Promise, hindi kita iiwan dito.',
      'Sige, naitala ang {subject}. Konting effort ngayon, ginhawa bukas.',
    ],
    surprise_quiz: [
      'Surprise quiz sa {subject}? Huminga ka, {name}. Best mo lang, sapat na yun.',
      'Biglaan, pero kaya mo to. Chill lang at magtiwala sa alam mo.',
      'Pop quiz sa {subject}? Okay {name}, huminga ka. Alam mo to, promise.',
      'Surprise quiz? Wag mag-panic, {name}. Magtiwala lang sa sarili mo.',
      'Biglang {subject} quiz. Game ka pa rin, {name}. Kalmado lang, kaya mo.',
      'Surprise quiz pala. Pero okay lang, {name}. Best effort lang, sapat na.',
      'Pop quiz sa {subject}? Relax, {name}. Kakayanin mo to.',
      'Surprise. Kaya mo yan, {name}. Basahin mong mabuti, isipin nang kalmado, sagot na.',
      'Biglaan na {subject} quiz, {name}. Huminga ka, kaya natin to.',
      'Uy, surprise quiz. Wag matakot, {name}. Andito lang ako, sabay tayo.',
      'Pop quiz sa {subject}? Okay lang, {name}. Magtiwala sa pinag-aralan mo.',
      'Surprise quiz, {name}? Chill. Best mo lang, walang sisihan after.',
      'Biglang quiz sa {subject}. Kaya to, {name}. Focus lang sa alam mo.',
      'Pop quiz pala. Pero kaya mo, {name}. Huminga, tapos sagot na.',
      'Surprise {subject} quiz? Game pa rin tayo, {name}. Kalmado, kaya mo.',
      'Pop quiz pala. Wag kabahan, {name}. Best mo lang gawin.',
      'Biglaan, {name}, pero okay lang. Kahit anong mangyari, proud pa rin ako sayo.',
      'Surprise quiz sa {subject}. Huminga, {name}. Isa-isang tanong lang.',
      'Uy, biglang quiz. Kalma lang, {name}. Alam mo to nang higit pa sa akala mo.',
      'Pop quiz pala. Tara {name}, kaya mo to. Kahit kabado, kaya mo pa rin.',
    ],
    quiz_due_soon: [
      'Malapit na ang {subject}, {name}. Kahit konting review ngayon, malaking tulong na.',
      'Uy {name}, paparating na ang {subject} quiz. Konting balik-aral muna.',
      'Paalala, {name}: malapit na ang {subject}. Wag nating kalimutan.',
      'Malapit na ang {subject}, {name}. Konti-konti lang tayo, wag mag-cram.',
      'Heads up, {name}. Malapit na ang {subject}. Tara, review muna ngayon.',
      'Uy {name}, {subject} na agad? Sige, handaan natin nang maaga.',
      'Paalala lang, {name}: parating na ang {subject}. Slow review, wag mag-panic.',
      'Malapit na yan, {name}. Review muna ng {subject} bago mag-relax.',
      'Heads up. Malapit na ang {subject} quiz, {name}. Isang topic kada araw, kaya yan.',
      'Uy {name}, wag kalimutan, malapit na ang {subject}. Konting review araw-araw.',
      'Paalala, {name}: paparating na ang {subject}. Andito ako pag kailangan mo.',
      'Malapit na ang {subject}, {name}. Huminga, may oras pa tayong maghanda.',
      'Parating na ang {subject} quiz, {name}. Tara, gawan natin ng review plan.',
      'Uy {name}, malapit na ang {subject}. Aral muna konti bago magpahinga.',
      'Heads up, {name}: review time na para sa {subject}. Dahan-dahan, kaya natin.',
      'Malapit na, {name}. Parating na ang {subject}. Maliit na hakbang ngayon, panalo bukas.',
      'Paalala lang, {name}: malapit na ang {subject}. Wag mahiyang humingi ng tulong.',
      'Uy {name}, {subject} na. Konting focus ngayon, konting stress sa quiz day.',
      'Paalala, {name}: parating na ang {subject}. Tara, simulan na natin ngayon.',
      'Malapit na ang {subject}, {name}. Promise, mas okay maghanda nang maaga.',
    ],
    quiz_scored_high: [
      '{score}. Ang galing, {name}. Bunga yan ng sipag mo. Ipagmalaki mo.',
      '{score}? Sobrang proud ako sayo, {name}.',
      '{score}, {name}? Ayan na ang resulta ng tiyaga mo. Bati muna tayo.',
      '{score}. Sabi ko na nga ba, kaya mo, {name}. Galing-galing.',
      '{score}. Panalo, {name}. I-treat mo ang sarili mo, deserve mo yan.',
      'Ang taas, {score}. Proud ako, {name}. Itaguyod mo lang yang sigasig na yan.',
      '{score}? Tuloy-tuloy lang to, {name}. Bilib talaga ako sayo.',
      '{score}, {name}. Nagbunga rin ang pagod mo. Ang sarap sa pakiramdam.',
      '{score}. Solid, {name}. Ngumiti ka muna, malaking bagay yan.',
      '{score}. Proud ako, {name}. Tuloy mo lang yan.',
      '{score}, {name}. Keep it up. Galing mo talaga.',
      'Ang ganda ng {score}, {name}. Tinapos mo nang maganda, ang galing mo.',
      '{score}? Ikaw ang nag-effort, {name}, deserve mo to.',
      'Panalo, {score}. Tandaan mo to, {name}, kaya mo pala lahat.',
      '{score}. Wow, {name}. Andito lang ako para makibahagi sa saya mo.',
      'Proud na proud akong seatmate mo, {name}. {score}, galing mo talaga.',
      '{score}. Ayan, bunga ng tiyaga, {name}. Ipagmalaki mo yan.',
      'Galing mo, {name}, {score}. Ang sarap sa pakiramdam, di ba? Deserve mo.',
      '{score}, {name}. Magaling. Tuloy mo lang ang ganitong sigasig.',
      'Ang taas niyan, {score}. Proud na proud ako, {name}. Tuloy mo lang to.',
    ],
    quiz_scored_mid: [
      '{score}, okay lang yan, {name}. Importante, tuloy-tuloy ang improve.',
      '{score}, {name}? Hindi naman masama yan. Konting tulak pa, mas taas next time.',
      'Okay yang {score}, {name}. Tara, tignan natin saan pwede mag-improve.',
      '{score}. Magandang simula, {name}. Tuloy-tuloy lang, papataas din yan.',
      'Hindi perfect pero okay, {score}. Proud pa rin ako, {name}.',
      '{score}, {name}? Pwede na. Konting review lang sa mahirap, game?',
      'Okay lang ang {score}, {name}. Hindi tayo nagmamadali, steady lang.',
      '{score}, nasa gitna pa, {name}, pero papunta tayo sa taas. Kaya yan.',
      'Okay to, {score}. Tandaan, {name}, may natutunan tayo sa bawat try.',
      '{score}, {name}. Hindi ka bumagsak, yun ang mahalaga. Tuloy lang.',
      'Ayos, {score}. Tara {name}, gawan natin ng plano para mas okay next time.',
      '{score}, sapat na yan, {name}. Konting tiyaga, taas din yan.',
      'Hindi naman pangit, {score}, {name}. Alamin lang natin yung mga na-miss.',
      '{score}, {name}? Pwede na talaga. Pero alam kong may higit pa sayo.',
      'Okay lang yan, {score}. Progreso pa rin yan, {name}. Proud ako.',
      '{score}, nasa gitna, {name}. Next time, konting taas pa ang target natin.',
      'Ayos ang effort, {score}. {name}, wag kang panghinaan, umaayos ka na.',
      '{score}, {name}. Tinapos mo, may halaga yun. Tara, review ulit nang magaan.',
      'Hindi naman masama, {score}. Konti-konti, {name}, gaganda din yan.',
      '{score}, okay na okay, {name}. Andito lang ako para sa susunod mong level.',
    ],
    quiz_scored_low: [
      'Hindi ka sinusukat ng {score}, {name}. Huminga. Subukan natin ulit, dahan-dahan.',
      '{score}, {name}? Okay lang yan, promise. Hindi pa to ang dulo ng lahat.',
      'Wag malungkot, {name}. {score} ngayon, pero may next time pa. Kaya natin.',
      'Hindi yan ang sukatan ng halaga mo, {name}. Andito lang ako para sayo.',
      'Okay ka lang, {name}? Pahinga muna, tapos bangon ulit tayo.',
      'Okay lang ma-disappoint, {name}. Pero tandaan, may natutunan ka pa rin. Laban.',
      '{score}, {name}. Hindi ka bobo, minsan talaga ganun ang araw. Ulitin natin.',
      'Wag kang susuko, {name}. {score} man ngayon, laban tayo next. Katabi mo ako.',
      '{score}, masakit, alam ko, {name}. Pero hindi ka nag-iisa. Sabay tayo ulit.',
      'Okay ka lang, {name}? {score} lang yan, hindi ikaw. Pahinga muna, tapos balik.',
      '{score}, {name}? Wag mong personalin. Aral lang to, kaya pa.',
      '{score}, {name}. Magpahinga ka kung kailangan, tapos bangon tayong dalawa.',
      'Hindi to failure, {name}, feedback lang. {score} ngayon, mas okay bukas.',
      'Wag kang susuko, {name}. {score} man, proud pa rin ako kasi sinubukan mo.',
      '{score}? Okay lang, {name}. Lahat ng magaling, dumaan din dito. Laban.',
      'Huminga, {name}. Isang quiz lang ang {score}. Hindi nito binabago kung gaano ka kagaling.',
      'Naiintindihan kita, {name}. {score} ngayon, pero bukas, bagong laban tayo.',
      '{score}, {name}. Tara, alamin natin saan nahirapan, walang sisihan. Sabay tayo.',
      'Wag masyadong malungkot, {name}. Hindi sukat ng buong journey mo ang isang {score}.',
      'Okay lang to, {name}. Marami pang chance. Hawak kita, bangon tayo ulit.',
    ],
  },
};

/** Used when a companion has no line for a trigger yet. Keeps things safe. */
const FALLBACK: DialogueBank = {
  home_greeting: ['Uy {name}, tara, simulan na natin ang araw.'],
  empty_quizzes: ['Wala pang naka-track. Magdagdag ka ng quiz para makapagsimula tayo.'],
  quiz_added: ['Naitala na ang {subject}.'],
  surprise_quiz: ['Surprise quiz sa {subject}. Kalmado lang, kaya mo to.'],
  quiz_due_soon: ['Paalala: malapit na ang {subject}.'],
  quiz_scored_high: ['Ang galing. {score}.'],
  quiz_scored_mid: ['Ayos, {score}. Tuloy lang.'],
  quiz_scored_low: ['{score} ngayon. Babawi tayo sa susunod.'],
};

function fill(line: string, vars: DialogueVars): string {
  return line
    .replace(/\{name\}/g, vars.name ?? 'there')
    .replace(/\{subject\}/g, vars.subject ?? 'it')
    .replace(/\{score\}/g, vars.score != null ? String(vars.score) : '');
}

function pick(lines: string[]): string {
  return lines[Math.floor(Math.random() * lines.length)];
}

/**
 * Get a single line of dialogue for the active companion reacting to a trigger.
 * Falls back to a generic line, then to home_greeting, so it never throws.
 */
export function getLine(
  companionId: CompanionId,
  trigger: TriggerKey,
  vars: DialogueVars = {},
): string {
  const bank = BANKS[companionId];
  const lines = bank[trigger] ?? FALLBACK[trigger] ?? FALLBACK.home_greeting!;
  return fill(pick(lines), vars);
}
